name: Java CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test_native:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      run: mvn clean install "-Djpackage.profile=true"

    - name: Install libfuse2
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2

    - name: Copy icon
      if: runner.os == 'Linux'
      run: cp src/main/resources/graphics/logo.png dist/Fribok/Fribok.png

    - name: Create AppImage (Linux)
      if: runner.os == 'Linux'
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        # Manually create the .desktop file
        cat > dist/Fribok/Fribok.desktop <<EOF
        [Desktop Entry]
        Type=Application
        Name=Fribok
        Exec=Fribok
        Icon=Fribok
        Categories=Office;Finance;
        EOF
        ./appimagetool-x86_64.AppImage dist/Fribok

    - name: Test Installer (Linux)
      if: runner.os == 'Linux'
      run: |
        chmod +x Fribok-x86_64.AppImage
        ./Fribok-x86_64.AppImage --version

    - name: Test Installer (Windows)
      if: runner.os == 'Windows'
      run: |
        msiexec /i dist/Fribok.msi /qn
        & "C:/Program Files/Fribok/Fribok.exe" --version

    - name: Test Installer (macOS)
      if: runner.os == 'macOS'
      run: |
        sudo hdiutil attach dist/Fribok.dmg
        /Volumes/Fribok/Fribok.app/Contents/MacOS/Fribok --version
        sudo hdiutil detach /Volumes/Fribok

    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: fribok-${{ matrix.os }}
        path: dist/*
