name: Java CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and test
      run: mvn clean install

  build_and_publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      run: mvn clean package -Djpackage.profile=true

    - name: Create AppImage (Linux)
      if: runner.os == 'Linux'
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage target/dist/Fribok

    - name: Test Installer (Linux)
      if: runner.os == 'Linux'
      run: |
        chmod +x Fribok-x86_64.AppImage
        ./Fribok-x86_64.AppImage --version

    - name: Test Installer (Windows)
      if: runner.os == 'Windows'
      run: |
        msiexec /i target/dist/Fribok.msi /qn
        & "C:/Program Files/Fribok/Fribok.exe" --version

    - name: Test Installer (macOS)
      if: runner.os == 'macOS'
      run: |
        sudo hdiutil attach target/dist/Fribok.dmg
        /Volumes/Fribok/Fribok.app/Contents/MacOS/Fribok --version
        sudo hdiutil detach /Volumes/Fribok

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fribok-${{ matrix.os }}
        path: target/dist/*
